-- Creacion de la tabla

CREATE TABLE APICULTURA(
    ID_COLMENA NUMBER NOT NULL,
    REINA_TEMPORADA NUMBER NOT NULL,
    DIRECCION_APIARIO VARCHAR2(100) NOT NULL,
    KG_MIEL NUMBER,
    NUMERO_ALZAS NUMBER,
    CONSTRAINT PK_ID_COLMENA PRIMARY KEY (ID_COLMENA)
);

-- Insertar registros
INSERT INTO APICULTURA VALUES (1, 2020, 'Rosales', 30, 2);
INSERT INTO APICULTURA VALUES (2, 2021, 'Rosales', 25, 2);
INSERT INTO APICULTURA VALUES (3, 2021, 'Barriales', 25, 2);
INSERT INTO APICULTURA VALUES (4, 2021, 'Rosales', 35, 3);
INSERT INTO APICULTURA VALUES (5, 2022, 'Barriales', 30, 3);
INSERT INTO APICULTURA VALUES (6, 2020, 'Barriales', 15, 1);